### ISSUE TITLE
Crash log 'ledger-manager' panicked 

### ISSUE THREAD

**Issue by EmreNOP** [openmina/openmina#990]
2024-12-04T21:18:49.191811Z  INFO openmina_core::log::action: time="1733347129083116388" kind="SnarkPoolWorkAdd"
verification time=5.17300246s (95 completed works)
2024-12-04T21:18:54.418114Z  INFO mina_tree::proofs::verification: time="1733347134418100152" verify_zkapp OK=true
95 transactions added to scan state:
- num_fee_transfer=1
- num_coinbase=1
- num_user_command=93
scan_state update:
- tree[00] level=0   1 completed jobs, a proof is emitted, tree is removed
- tree[03] level=1   2 completed jobs (DONE)
           level=0   1 new merge jobs (TODO)
- tree[06] level=2   4 completed jobs (DONE)
           level=1   2 new merge jobs (TODO)
- tree[09] level=3   8 completed jobs (DONE)
           level=2   4 new merge jobs (TODO)
- tree[12] level=4  16 completed jobs (DONE)
           level=3   8 new merge jobs (TODO)
- tree[15] level=5  32 completed jobs (DONE)
           level=4  16 new merge jobs (TODO)
- tree[18] level=6  64 completed jobs (DONE)
           level=5  32 new merge jobs (TODO)
- tree[21] level=7  60 completed jobs (DONE)
           level=6  30 new merge jobs (TODO)
- tree[23] level=7  94 new base jobs (TODO), total_nbase_jobs=128
           level=7 has the following jobs (in this order):
           CB|31 CMD|CB|FT|93 CMD|FT
scan_state update: (2nd set of jobs, new transactions didn't fit in latest/current tree)
- tree[21] level=7   2 completed jobs (DONE)
           level=6   1 new merge jobs (TODO)
- tree[24] level=7   1 new base jobs (TODO), total_nbase_jobs=1
           level=7 has the following jobs (in this order):
           CB|127 EMPTY
thread 'ledger-manager' panicked at ledger/src/mask/mask_impl.rs:228:17:
mask has 1 children that must be unregistered first
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'ledger-manager' panicked at ledger/src/mask/mask.rs:79:47:
lock failed: "Poisoned(..)"
stack backtrace:
   0:     0x560ed7694995 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd736fd5964392270
   1:     0x560ed76bf63b - core::fmt::write::hc6043626647b98ea
   2:     0x560ed76912ef - std::io::Write::write_fmt::h0d24b3e0473045db
   3:     0x560ed769476e - std::sys_common::backtrace::print::h45eb8174d25a1e76
   4:     0x560ed7695cb9 - std::panicking::default_hook::{{closure}}::haf3f0170eb4f3b53
   5:     0x560ed7695a5a - std::panicking::default_hook::hb5d3b27aa9f6dcda
   6:     0x560ed7696153 - std::panicking::rust_panic_with_hook::h6b49d59f86ee588c
   7:     0x560ed7696034 - std::panicking::begin_panic_handler::{{closure}}::hd4c2f7ed79b82b70
   8:     0x560ed7694e59 - std::sys_common::backtrace::__rust_end_short_backtrace::h2946d6d32d7ea1ad
   9:     0x560ed7695d67 - rust_begin_unwind
  10:     0x560ed58e9203 - core::panicking::panic_fmt::ha02418e5cd774672
  11:     0x560ed58e96f6 - core::result::unwrap_failed::h55f86ada3ace5ed2
  12:     0x560ed6b9b66c - mina_tree::mask::mask::Mask::remove_child_uuid::h1c73d7982a802072
  13:     0x560ed6b9a0bb - <mina_tree::mask::mask::Mask as core::ops::drop::Drop>::drop::h9126ee4daed33bf7
  14:     0x560ed653b23a - <alloc::collections::btree::map::IntoIter<K,V,A> as core::ops::drop::Drop>::drop::ha0051dbdf2c6d861
  15:     0x560ed679a677 - core::ptr::drop_in_place<node::ledger::ledger_service::LedgerCtx>::hfd72924e37209b11
  16:     0x560ed6793b96 - core::ptr::drop_in_place<node::ledger::ledger_manager::LedgerManager::spawn::{{closure}}>::hba9d5aed6113abb0
  17:     0x560ed6791da7 - std::sys_common::backtrace::__rust_begin_short_backtrace::he91021dc517ab372
  18:     0x560ed66b30ca - core::ops::function::FnOnce::call_once{{vtable.shim}}::h33fd83f0e95366cd
  19:     0x560ed7699b6b - std::sys::pal::unix::thread::Thread::new::thread_start::hb85dbfa54ba503d6
  20:     0x7f2c5a3c7fa3 - start_thread
  21:     0x7f2c5a16f06f - clone
  22:                0x0 - <unknown>
thread 'ledger-manager' panicked at library/core/src/panicking.rs:227:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
Aborted (core dumped)

**Comment by tizoc** [comment]
Hi @EmreNOP. Which version was this? and do you have more logs? seems something else (like another thread panicking) happened before leading to that lock being poisoned.
